name: Update Database Entry
description: Report incorrect information or request updates to an existing database entry.
title: "[Update]: "
labels: ["update"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form to report issues with existing database entries or request updates.

  - type: input
    id: database_name
    attributes:
      label: Database Name
      description: Which database entry needs to be updated?
      placeholder: e.g., LIVE Video Quality Database
    validations:
      required: true

  - type: input
    id: database_url
    attributes:
      label: Database Page URL
      description: Link to the database entry on the QUALINET Databases website
      placeholder: https://qualinet.github.io/databases/...
    validations:
      required: false

  - type: dropdown
    id: issue_type
    attributes:
      label: Type of Update
      description: What kind of update is needed?
      options:
        - Broken/outdated link
        - Incorrect information
        - Database no longer available
        - Additional information to add
        - Other
    validations:
      required: true

  - type: textarea
    id: current_info
    attributes:
      label: Current Information
      description: What is the current (incorrect) information?
    validations:
      required: false

  - type: textarea
    id: correct_info
    attributes:
      label: Correct/Updated Information
      description: What should the information be updated to?
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context or information that might be helpful.
    validations:
      required: false
